### ISSUE TITLE
Optimism Mainnet and Kovan Test Network withdrawal

### ISSUE THREAD

**Issue by hyfong8687** [ethereum-optimism/community-hub#201]
I have posted my question in the discord but have not yet received any reply. Can you answer my following question:

I am using the Optimism Mainnet for the withdrawal. But your tutorial is using the Kovan Test Network. Does it make any difference? Please advise.

**Comment by qbzzt** [comment]
I apologize. The sole difference is supposed to be the wait time. It's one minute on Kovan and a week on the production network. Other steps, such as finalizing the transaction, are exactly the same.

**Comment by hyfong8687** [comment]
On finalizing the transaction, the Optimism Mainnet did not require me to execute " Ready for relay" in the L2 to L1 Message Relayer. In fact, the transaction was completed within the Optimism Mainnet. 

In the L2 to L1 Message Relayer, it shows the status is "Waiting". when I tried to press the "execute" button, nothing happen. What should I do? Please advise.

**Comment by qbzzt** [comment]
I looked at our support issues, there was a period that L2 transactions weren't written to L1. This delays withdrawals because the challenge period only starts with the transaction is written to L1 (and is therefore available to be challenged).

Please go to https://community.optimism.io/docs/users/gateway.html#when-is-the-withdrawal-ready and perform the second bullet point of step 7 to see when your transaction was actually written to L1.

**Comment by hyfong8687** [comment]
My transaction was actually written to L1, please see the following Transaction Hash: 0x872d6ad0d1d175e191b0f4e42f7eb60d3ec0b8e6a2e69ef988cd6ae086ec0992

**Comment by qbzzt** [comment]
If you look in that transaction (https://optimistic.etherscan.io/tx/0x872d6ad0d1d175e191b0f4e42f7eb60d3ec0b8e6a2e69ef988cd6ae086ec0992) and click the **L1 Submission Tx Hash:**, you'll see that the L1 transaction was actually submitted less than a week ago: https://etherscan.io/tx/0xc32d08ea5b1c5855cd4037bcdaa93d24440f203c031642bc8a397a8e3de8c33d . That is the reason your withdrawal is not available yet, it's a week from the L1 transaction that publishes the details.
