### ISSUE TITLE
optimism withdrawl still pending

### ISSUE THREAD

**Issue by vikassuhalka** [ethereum-optimism/community-hub#202]
0x09C060927Ef69aE06627aa95543703E0c86EFcB7    its my eth address

its been over 8 days above the challenge period and my optimism eth withdrawl still pending..pls help

**Comment by qbzzt** [comment]
I looked at our support issues, there was a period that L2 transactions weren't written to L1. This delays withdrawals because the challenge period only starts with the transaction is written to L1 (and is therefore available to be challenged).

Please go to https://community.optimism.io/docs/users/gateway.html#when-is-the-withdrawal-ready and perform the second bullet point of step 7 to see when your transaction was actually written to L1?

**Comment by vikassuhalka** [comment]
ok...but do i need to perform any action or just wait for the withdrawal to happen automatically????

**Comment by qbzzt** [comment]
You need to finalize the transaction, as explained here: https://community.optimism.io/docs/users/gateway.html#finalizing-the-withdrawal

**Comment by vikassuhalka** [comment]
okay got it....
