### ISSUE TITLE
L2 FAQ/Noob Questions

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/community-hub#26]
Would like to pick out the best questions from this thread and give them answers:

https://twitter.com/AdamScochran/status/1365365202749915136

**Comment by platocrat** [comment]
my list:

1. One-week withdrawal times, due to finality challenges?
2. Will tools like MetaMask need to add custom instrumentation to use Optimistic contracts or is that handled by proxy contract mapping?
3. What the heck are sequences and transaction aggregators?
    3a..  Is it an open fee market like mining, or can an app define their own sequencers/transaction aggregator and force set usage fees?
4. Because Optimisim creates a new arbitrage market with a 1 week settlement, it seems it may not improve the gas utilization on mainnet (as we'll continue to see arb) but can allow new high throughput, low cost types of apps on Optimism. Is that the expected outcome?

I think these are the most relevant without going too much outside of the realm of OE

**Comment by TransmissionsDev** [comment]
i would include:
- If an asset is "in the L2" what wallet address does the L1 see it in (on Etherscan)?
- Will there still be large fees to deposit into the L2? Is that deposit separate for each app, or once you are in the L2 can you move affordably to other L2 apps?
- Are offline computations being done by some set of validators? If so who are there?
- Will tools like Metamask need to add custom instrumentation to use Optimistic contracts or is that handled by proxy contract mapping?

**Comment by platocrat** [comment]
> but these are a little less optimism specific. maybe i just answer these in a thread?

I think these can all be added under the FAQs page (_not_ in the FAQs channel)

**Comment by platocrat** [comment]
This is another quite stale issue that I think are slightly off base from our current priorities.
However, the core themes of these questions will be getting added in waves to as we expand the protocol and developer documentation.
