### ISSUE TITLE
Translate documentations into Japanese

### ISSUE THREAD

**Issue by Felix471** [ethereum-optimism/community-hub#281]
Hi there, I am planning to translate tutorials and documentations into Japanese, and I am wondering how I can submit my translations. I am confident about the accuracy and professionalism of my translation, but I am not very familiar with the features of Github, so I would like to ask you guys where and how to start.
I also speak Chinese (and I found out Chinese Translation has already started), so I would deeply appreciate it if any of you guys in the Chinese community could offer advice on templates or things like that.

**Comment by smartcontracts** [comment]
Hi there, I'm going to create an issue today explaining the current situation with the translations and our plans for the community hub. Ideally we will be using software like Crowdin to make translations easier. We want to wait until our plans for the community hub update are more solidified so that we don't have a lot of people doing translations that get thrown away.

**Comment by smartcontracts** [comment]
Announcement regarding our plan for the next few weeks: https://github.com/ethereum-optimism/community-hub/discussions/283

**Comment by qbzzt** [comment]
Sorry for the delay. We now have [CrowdIn](https://crowdin.com/project/optimism-help-center) and we'd love a Japanese translation. 


ありがとうございます
