### ISSUE TITLE
Why doesn't the op have its own currency? I see that online and test chain transactions are displayed with eth?

### ISSUE THREAD

**Issue by coder-chenda** [ethereum-optimism/community-hub#418]

**Comment by qbzzt** [comment]
This is more a question for our discord (https://discord-gateway.optimism.io/), but the reason is that we aren't trying to push a token, we are trying to make a blockchain that is as easy for Ethereum users to use as possible, except cheaper and faster. It's easier for users if we use the same ETH, and you just need to bridge it.
