### ISSUE TITLE
User test the "integration docs"

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/community-hub#7]
## Context.

We are currently directing people away from testing on Testnet, towards running locally with up.sh (Docker)

We want to ensure that this is a well documented, easy to follow process, without unexpected snags.  

## Description

It would be great to get some QA on these integration docs: http://community.optimism.io/docs/integration.html

**Todo:**
1. Follow the steps exactly as outlined in the document above. 
2. Make a not about any of the following: 
  - Instructions that are unclear
  - steps/commands that don't work as expected
  - Over reliance on external resources (ie. you should be able to run through the full process with just the information available on this page). 

## This is done when

The items above are recorded in a single document.

**Comment by platocrat** [comment]
My notes/questions are delineated by section of docs

### Overview

* Point 2 can be clearer by using the description of what a full L2 is from section 2: "Integrate full local copy of Optimistic Ethereum (OE): get those contracts running on a local instance of the full L2 system, including a local L1 chain, sequencer, etc."

### 1. Running on the OVM

* Second paragraph: could clearly explain that the docs will expect you to run through some tutorial (whether the `optimism-tutorial` or Scopelift's (if still relevant)) or already have your optimism contracts ready to go.
        - Perhaps rewrite the last sentence as: "For the rest of this documentation, we'll expect you to have your prewritten OVM-compatible contracts ready to go. If you need help writing them, you can follow our `optimism-tutorial` [here](https://github.com/ethereum-optimism/optimism-tutorial), which should be pretty seamless."
* In [Running on the OVM](http://community.optimism.io/docs/integration.html#_1-running-on-the-ovm), there's a typo in the third paragraph: "but, these packages NPM have got you covered:" should be "But, these NPM packages have got you covered:"
* There should be links to GitHub pages for those npm packages:
        - [`@eth-optimism/solc`](https://www.npmjs.com/package/@eth-optimism/solc): exports OVM compiler for `solidity@0.5/0.6/0.7`
        - [`@eth-optimism/ovm-toolchain`](https://www.npmjs.com/package/@eth-optimism/ovm-toolchain): exports "OVM-ified" `waffleV3.mockProvider` and `ganache` packages which will work with contracts output by the compiler.
* Can Optimism users opt-in to whether to use `@eth-optimism/solc` or `@eth-optimism/ovm-toolchain`? Or is one NPM package recommended over the over? Asked becuase the Scopelift tutorial is still being referenced. I thought that tutorial was now considered outdated because it used the `toolchain` instead of the Optimism's new `solc` version?
* The italicized note before the troubleshoot section:
        - Could remove the double backslashes "//" at the beginning
        - Break up first two points into 2 separate sentences

#### Troubleshooting

* First line can be more clearly rewritten as:
        - "There are some small differences between the EVM and the OVM (such as removing usage of EVM opcodes which do not have an equivalent in OVM L2.) which could require some debugging at this stage. For help with these, you can check out the following resources:"
* Referencing the Scopelift tut here again, but is this tutorial still helpful? (see question about using `solc` vs. `toolchain`).
* Third resource could use embedded link:
        - For a [DEEP robust explanation](https://hackmd.io/Inuu-T_UTsSXnzGtrLR8gA) of ALL OVM <> EVM incompatabilities

### 2. Running on Optimistic Ethereum

#### Local deployment

* Before introducing the commands, make sure to clarify that Docker must be running :); rewrite the second sentence as, "Remember to make sure docker is running before running any commands. You can check out the [full usage page](https://github.com/ethereum-optimism/optimism-integration#usage) for the full list of commands, but the basic commands to run are:"
* Having the E2E system running locally isn't as satisfactory as having connected to run your contracts. So, there should be some additional text that guides the user on how this is done. (Looks like the specifics for how to do this are within `optimism-integration` and `integration-tests`? Is yes, adding the most relevant portions of those README's here would be a helpful.)

##### Gotchas

* Is this chainID unique only to the local instance? Or does this chainID appear elsewhere?
* When will we know about how much or what to expect forL2 fees?

### 3. Bridging L1 and L2

* Clarify first sentence: "The last step to get our full local copy of OE ready to deploy is, if necessary, work on connecting L1 and L2.
* This section can use some TLC to clarify message passing.
* Correcting all links to embedded links:
    1. Depositing SNX into L2
        * [Initiating on L1](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToOptimism.sol#L190-L205)
        * [This leads to recieving on L2](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToBase.sol#L111-L115)
    2. Migrate SNX Escrow entries to L2 (transferring large amounts of state from L1->L2):
        * [Initiating on L1](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToOptimism.sol#L207-L236)
        * [This leads to receiving on L2](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToBase.sol#L98-L108)
    3. Withdrawing SNX to L1:
        * [Burning L2 SNX and initiating the withdrawal on L2](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToBase.sol#L76-L94)
        * [Completing the Withdrawal on L1](https://github.com/Synthetixio/synthetix/blob/49427867e6d50886e0c8725e15c8b87e25aa6f8c/contracts/SynthetixBridgeToOptimism.sol#L126-L136)
